---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: vsphere-csi-controller
  namespace: {{ .Release.Namespace }}
labels:
  gardener.cloud/role: controlplane
  app: kubernetes
  role: csi-plugin-controller
  high-availability-config.resources.gardener.cloud/type: server
spec:
  serviceName: vsphere-csi-controller
  revisionHistoryLimit: 1
  replicas: {{ .Values.replicas }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: vsphere-csi-controller
  template:
    metadata:
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        gardener.cloud/role: controlplane
        app: vsphere-csi-controller
        role: vsphere-csi
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/to-private-networks: allowed
        networking.gardener.cloud/to-shoot-apiserver: allowed
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - vsphere-csi-controller
              topologyKey: "kubernetes.io/hostname"
      automountServiceAccountToken: false
      containers:
        - name: csi-attacher
          image: {{ index .Values.images "csi-attacher" }}
          args:
            - "--v=4"
            - "--timeout=300s"
            - "--csi-address=/csi/csi.sock"
            - "--leader-election"
            - "--leader-election-namespace=kube-system"
            - --kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
{{- if .Values.resources.attacher }}
          resources:
{{ toYaml .Values.resources.attacher | indent 12 }}
{{- end }}
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
              name: kubeconfig-csi-attacher
              readOnly: true
{{- if .Values.resizerEnabled }}
        - name: csi-resizer
          image: {{ index .Values.images "csi-resizer" }}
          args:
            - "--v=4"
            - "--timeout=300s"
            - "--handle-volume-inuse-error=false"
            - "--csi-address=/csi/csi.sock"
            - "--kube-api-qps=100"
            - "--kube-api-burst=100"
            - "--leader-election"
            - "--leader-election-namespace=kube-system"
            - --kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
{{- if .Values.resources.resizer }}
          resources:
{{ toYaml .Values.resources.resizer | indent 12 }}
{{- end }}
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
              name: kubeconfig-csi-resizer
              readOnly: true
{{- end }}
        - name: vsphere-csi-controller
          image: {{ index .Values.images "vsphere-csi-driver-controller" }}
          args:
            - "--fss-name=internal-feature-states.csi.vsphere.vmware.com"
            - "--fss-namespace=$(CSI_NAMESPACE)"
            - --kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: X_CSI_MODE
              value: "controller"
            - name: VSPHERE_CSI_CONFIG
              value: "/etc/cloud/csi-vsphere.conf"
            - name: LOGGER_LEVEL
              value: "{{ .Values.loggerLevel }}" # Options: DEVELOPMENT, PRODUCTION
            - name: INCLUSTER_CLIENT_QPS
              value: "100"
            - name: INCLUSTER_CLIENT_BURST
              value: "100"
            - name: CSI_NAMESPACE
              value: kube-system
{{- if .Values.resources.controller }}
          resources:
{{ toYaml .Values.resources.controller | indent 12 }}
{{- end }}
          volumeMounts:
            - mountPath: /etc/cloud
              name: vsphere-config-volume
              readOnly: true
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
              name: kubeconfig-vsphere-csi-controller
              readOnly: true
          ports:
            - name: healthz
              containerPort: 9808
              protocol: TCP
            - name: prometheus
              containerPort: 2112
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 3
        - name: vsphere-csi-syncer
          image: {{ index .Values.images "vsphere-csi-driver-syncer" }}
          args:
            - "--leader-election"
            - "--leader-election-namespace=kube-system"
            - --kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
            - "--fss-name=internal-feature-states.csi.vsphere.vmware.com"
            - "--fss-namespace=$(CSI_NAMESPACE)"
          env:
            - name: FULL_SYNC_INTERVAL_MINUTES
              value: "30"
            - name: VSPHERE_CSI_CONFIG
              value: "/etc/cloud/csi-vsphere.conf"
            - name: LOGGER_LEVEL
              value: "{{ .Values.loggerLevel }}" # Options: DEVELOPMENT, PRODUCTION
            - name: INCLUSTER_CLIENT_QPS
              value: "100"
            - name: INCLUSTER_CLIENT_BURST
              value: "100"
            - name: CSI_NAMESPACE
              value: kube-system
{{- if .Values.resources.syncer }}
          resources:
{{ toYaml .Values.resources.syncer | indent 12 }}
{{- end }}
          volumeMounts:
            - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
              name: kubeconfig-csi-syncer
              readOnly: true
            - mountPath: /etc/cloud
              name: vsphere-config-volume
              readOnly: true
        - name: csi-liveness-probe
          image: {{ index .Values.images "liveness-probe" }}
          args:
            - "--v=4"
            - "--csi-address=/csi/csi.sock"
{{- if .Values.resources.liveness }}
          resources:
{{ toYaml .Values.resources.liveness | indent 12 }}
{{- end }}
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: csi-provisioner
          image: {{ index .Values.images "csi-provisioner" }}
          args:
            - "--v=4"
            - "--timeout=300s"
            - "--csi-address=/csi/csi.sock"
            - "--kube-api-qps=100"
            - "--kube-api-burst=100"
            - "--feature-gates=Topology=true"
            - "--strict-topology"
            - "--default-fstype=ext4"
            - "--leader-election"
            - "--leader-election-namespace=kube-system"
            - --kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
{{- if .Values.resources.provisioner }}
          resources:
{{ toYaml .Values.resources.provisioner | indent 12 }}
{{- end }}
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
              name: kubeconfig-csi-provisioner
              readOnly: true
{{- if .Values.volumesnapshots.enabled }}
        - name: csi-snapshotter
          image: {{ index .Values.images "csi-snapshotter" }}
          args:
            - "--v=4"
            - "--kube-api-qps=100"
            - "--kube-api-burst=100"
            - "--timeout=300s"
            - "--csi-address=/csi/csi.sock"
            - --kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
            - "--leader-election"
            - "--leader-election-namespace=kube-system"
            - "--snapshot-name-prefix={{ .Release.Namespace }}"
{{- if .Values.resources.snapshotter }}
          resources:
{{ toYaml .Values.resources.snapshotter | indent 12 }}
{{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
              name: kubeconfig-csi-snapshotter
              readOnly: true
{{- end }}
      volumes:
        - name: kubeconfig-vsphere-csi-controller
          projected:
            defaultMode: 420
            sources:
            - secret:
                items:
                - key: kubeconfig
                  path: kubeconfig
                name: {{ .Values.global.genericTokenKubeconfigSecretName }}
                optional: false
            - secret:
                items:
                - key: token
                  path: token
                name: shoot-access-vsphere-csi-controller
                optional: false
        - name: kubeconfig-csi-attacher
          projected:
            defaultMode: 420
            sources:
            - secret:
                items:
                - key: kubeconfig
                  path: kubeconfig
                name: {{ .Values.global.genericTokenKubeconfigSecretName }}
                optional: false
            - secret:
                items:
                - key: token
                  path: token
                name: shoot-access-csi-attacher
                optional: false
        - name: kubeconfig-csi-provisioner
          projected:
            defaultMode: 420
            sources:
            - secret:
                items:
                - key: kubeconfig
                  path: kubeconfig
                name: {{ .Values.global.genericTokenKubeconfigSecretName }}
                optional: false
            - secret:
                items:
                - key: token
                  path: token
                name: shoot-access-csi-provisioner
                optional: false
        - name: kubeconfig-csi-syncer
          projected:
            defaultMode: 420
            sources:
            - secret:
                items:
                - key: kubeconfig
                  path: kubeconfig
                name: {{ .Values.global.genericTokenKubeconfigSecretName }}
                optional: false
            - secret:
                items:
                - key: token
                  path: token
                name: shoot-access-csi-syncer
                optional: false
        {{- if .Values.volumesnapshots.enabled }}
        - name: kubeconfig-csi-snapshotter
          projected:
            defaultMode: 420
            sources:
            - secret:
                items:
                - key: kubeconfig
                  path: kubeconfig
                name: {{ .Values.global.genericTokenKubeconfigSecretName }}
                optional: false
            - secret:
                items:
                - key: token
                  path: token
                name: shoot-access-csi-snapshotter
                optional: false
        {{- end }}
        - name: kubeconfig-csi-resizer
          projected:
            defaultMode: 420
            sources:
            - secret:
                items:
                - key: kubeconfig
                  path: kubeconfig
                name: {{ .Values.global.genericTokenKubeconfigSecretName }}
                optional: false
            - secret:
                items:
                - key: token
                  path: token
                name: shoot-access-csi-resizer
                optional: false
        - name: vsphere-config-volume
          secret:
            secretName: csi-vsphere-config
        - name: socket-dir
          emptyDir: {}
